const USER_ROLES = ["SUPERADMIN", "ADMIN", "MANAGER", "ANALYST", "USER"];
const USER_STATUSES = ["ACTIVE", "INVITED", "SUSPENDED"];

const TRANSPORT_MODES = ["ROAD", "RAIL", "AIR", "OCEAN"];
const SHIPMENT_STATUSES = ["PLANNED", "IN_TRANSIT", "DELAYED", "DELIVERED"];
const SUPPLIER_RISK_LEVELS = ["LOW", "MEDIUM", "HIGH"];
const SUPPLIER_VERIFICATION_STATUSES = ["VERIFIED", "PENDING", "ACTION_REQUIRED"];

const EMISSION_SCOPES = [1, 2, 3];
const EMISSION_SOURCE_TYPES = [
  "SHIPMENT",
  "SUPPLIER",
  "SCOPE1_STATIONARY_FUEL",
  "SCOPE1_FLEET",
  "SCOPE2_ELECTRICITY",
  "LEDGER",
  "OFFSET",
  "ADJUSTMENT",
];

const OFFSET_PROJECT_STATUSES = ["DRAFT", "PUBLISHED", "ARCHIVED", "SOLD_OUT", "ACTIVE", "INACTIVE"];
const OFFSET_TRANSACTION_TYPES = ["PURCHASE", "RETIREMENT"];
const OFFSET_TRANSACTION_STATUSES = ["COMPLETED", "PENDING", "FAILED"];

module.exports = {
  USER_ROLES,
  USER_STATUSES,
  TRANSPORT_MODES,
  SHIPMENT_STATUSES,
  SUPPLIER_RISK_LEVELS,
  SUPPLIER_VERIFICATION_STATUSES,
  EMISSION_SCOPES,
  EMISSION_SOURCE_TYPES,
  OFFSET_PROJECT_STATUSES,
  OFFSET_TRANSACTION_TYPES,
  OFFSET_TRANSACTION_STATUSES,
};
