const USER_ROLES = ["SUPERADMIN", "OWNER", "ADMIN", "MANAGER", "ANALYST", "USER", "DATA_ENTRY", "VIEWER", "AUDITOR"];
const USER_STATUSES = ["ACTIVE", "INVITED", "SUSPENDED"];

const TRANSPORT_MODES = ["ROAD", "RAIL", "AIR", "OCEAN"];
const SHIPMENT_STATUSES = ["DRAFT", "SUBMITTED", "PLANNED", "IN_TRANSIT", "DELAYED", "DELIVERED", "CANCELLED", "ARCHIVED"];
const SUPPLIER_RISK_LEVELS = ["LOW", "MEDIUM", "HIGH"];
const SUPPLIER_STATUSES = [
  "draft",
  "invited",
  "submitted",
  "under_review",
  "verified",
  "rejected",
  "needs_update",
  "approved",
  "high_risk",
  "archived",
];
const SUPPLIER_VERIFICATION_STATUSES = [
  "pending",
  "self_reported",
  "third_party_verified",
  "expired",
  "rejected",
  "VERIFIED",
  "PENDING",
  "ACTION_REQUIRED",
];
const SUPPLIER_INVITATION_STATUSES = [
  "not_sent",
  "sent",
  "opened",
  "submitted",
  "overdue",
  "expired",
  "SENT",
  "ACCEPTED",
  "NOT_SENT",
];
const SUPPLIER_QUESTIONNAIRE_STATUSES = ["not_sent", "sent", "opened", "submitted", "overdue", "expired"];
const SUPPLIER_EVIDENCE_TYPES = [
  "iso_14001_certificate",
  "sbti_commitment",
  "ghg_inventory",
  "esg_report",
  "audit_report",
  "utility_fuel_data",
  "carbon_reduction_plan",
  "supplier_questionnaire_answers",
  "other",
];
const SUPPLIER_EVIDENCE_STATUSES = ["requested", "submitted", "under_review", "verified", "rejected", "expired"];

const EMISSION_SCOPES = [1, 2, 3];
const EMISSION_SOURCE_TYPES = [
  "SHIPMENT",
  "SUPPLIER",
  "SCOPE1_STATIONARY_FUEL",
  "SCOPE1_FLEET",
  "SCOPE1_FUGITIVE",
  "SCOPE1_PROCESS",
  "SCOPE2_ELECTRICITY",
  "SCOPE2_PURCHASED_HEAT",
  "SCOPE3_BUSINESS_TRAVEL",
  "SCOPE3_EMPLOYEE_COMMUTING",
  "SCOPE3_PURCHASED_GOODS_SERVICES",
  "SCOPE3_WASTE",
  "SCOPE3_UPSTREAM_TRANSPORTATION",
  "SCOPE3_DOWNSTREAM_TRANSPORTATION",
  "SCOPE3_FUEL_ENERGY_RELATED",
  "ACTIVITY",
  "LEDGER",
  "OFFSET",
  "ADJUSTMENT",
];

const OFFSET_PROJECT_STATUSES = [
  "DRAFT",
  "PENDING_REVIEW",
  "PUBLISHED",
  "PAUSED",
  "SOLD_OUT",
  "ARCHIVED",
  "ACTIVE",
  "INACTIVE",
];
const MARKETPLACE_VERIFICATION_STATUSES = [
  "UNVERIFIED",
  "SELF_REPORTED",
  "THIRD_PARTY_VERIFIED",
  "REGISTRY_VERIFIED",
  "REJECTED",
  "EXPIRED",
];
const OFFSET_TRANSACTION_TYPES = ["PURCHASE", "RETIREMENT"];
const OFFSET_TRANSACTION_STATUSES = ["DRAFT", "PENDING", "RESERVED", "COMPLETED", "FAILED", "CANCELLED", "REFUNDED"];

module.exports = {
  USER_ROLES,
  USER_STATUSES,
  TRANSPORT_MODES,
  SHIPMENT_STATUSES,
  SUPPLIER_RISK_LEVELS,
  SUPPLIER_STATUSES,
  SUPPLIER_VERIFICATION_STATUSES,
  SUPPLIER_INVITATION_STATUSES,
  SUPPLIER_QUESTIONNAIRE_STATUSES,
  SUPPLIER_EVIDENCE_TYPES,
  SUPPLIER_EVIDENCE_STATUSES,
  EMISSION_SCOPES,
  EMISSION_SOURCE_TYPES,
  OFFSET_PROJECT_STATUSES,
  MARKETPLACE_VERIFICATION_STATUSES,
  OFFSET_TRANSACTION_TYPES,
  OFFSET_TRANSACTION_STATUSES,
};
