const mongoose = require("mongoose");
const { withBaseSchema } = require("./helpers/model.utils");

const reportSchema = withBaseSchema({
  companyId: { type: String, ref: "Company", required: true, index: true },
  name: { type: String, required: true, trim: true },
  reportName: { type: String, default: null, trim: true },
  type: {
    type: String,
    enum: [
      "ESG",
      "COMPLIANCE",
      "ANALYTICS",
      "CUSTOM",
      "esg_pdf",
      "scope_export_csv",
      "custom_extract",
      "carbon_ledger",
      "supplier_esg",
      "shipment_emissions",
      "marketplace_retirement",
    ],
    required: true,
    index: true,
  },
  reportType: { type: String, default: null, trim: true, index: true },
  format: { type: String, enum: ["CSV", "PDF", "JSON", "csv", "pdf", "json"], default: "CSV" },
  outputFormat: { type: String, enum: ["CSV", "PDF", "JSON", "csv", "pdf", "json"], default: null },
  reportingPeriodStart: { type: Date, default: null },
  reportingPeriodEnd: { type: Date, default: null },
  inclusionPolicy: { type: String, enum: ["approved_only", "all_records_with_warning", "all_records"], default: "approved_only", index: true },
  generatedAt: { type: Date, default: Date.now },
  status: {
    type: String,
    enum: ["READY", "PROCESSING", "FAILED", "queued", "generating", "completed", "failed", "archived"],
    default: "completed",
    index: true,
  },
  generatedBy: { type: String, ref: "User", default: null },
  completedAt: { type: Date, default: null },
  failedAt: { type: Date, default: null },
  failureReason: { type: String, default: null, trim: true },
  fileUrl: { type: String, default: null, trim: true },
  storageKey: { type: String, default: null, trim: true },
  downloadUrl: { type: String, required: true },
  recordCounts: { type: Object, default: {} },
  scopeTotals: { type: Object, default: {} },
  dataQualitySummary: { type: Object, default: {} },
  sampleFactorCount: { type: Number, default: 0 },
  missingFactorCount: { type: Number, default: 0 },
  unapprovedRecordCount: { type: Number, default: 0 },
  staleFactorCount: { type: Number, default: 0 },
  methodologyVersion: { type: String, default: "carbonflow-methodology-v1", trim: true },
  reportVersion: { type: String, default: "1.0", trim: true },
  auditTrailId: { type: String, default: null, trim: true },
  metadata: { type: Object, default: {} },
}, {
  collection: "reports",
});

module.exports = mongoose.models.Report || mongoose.model("Report", reportSchema);
